language: r
r: 3.5
cache: packages
dist: xenial

before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - echo ${COMMITTER_EMAIL}
  - echo ${AUTHOR_NAME}
  - export COMMITTER_EMAIL="${!AUTHOR_NAME}" # email stored in travis custom variable

script:
  - echo "hi" #bash build.sh

#after_success:
#  - bash sendmail.sh
notifications:
  email:
    on_pull_requests: always

